### ISSUE TITLE
[Question] Commands without 'AT' prefix

### ISSUE THREAD

**Issue by n-elia** [warthog618/modem#11]
Hi,
first of all thanks for sharing this great module.
I would like to know your opinion about the following situation.

When using the `at` package to communicate with a modem, which is your suggested way of sending raw data to the modem itself? Example: I issue the command to send data over UDP and, after its execution, the modem listens for a message. Which is a legit way of sending that message to the modem?

[I added a commandOption](https://github.com/n-elia/modem/commit/e5cd7fc9730ad5ba7de4cc3886d975e5d5c2f0bc) to exclude the 'AT' prefix from the command, such that I am able to send command without 'AT' prefix when I need it.
The reason why I did that is that `at` package manages lots of things (e.g. escape characters, catching the modem response) which are perhaps already setup into `at` configuration and which I should duplicate to achieve the same results.

I think that sending data without 'AT' prefix is out of the scopes of your package, however may this approach be considered legit? In case it is not, do you have any suggestion?

Thank you,
Nicola

**Comment by warthog618** [comment]
This is a similar use case to the GSM commands, but I would need a more complete description of the message exchange for your use case to be sure.  In that case the modem does not reply to the initial AT command with a usual response, but with a ">" prompt.  This requires special handling within the `at` package, as the `Command()` method always waits for the standard AT response, and it blocks other commands being issued to the modem via a subsequent `Command()` while it waits.
There are functions provided in `at` to deal with the SMS behaviour, the external one being `SMSCommand()`.
I would look at doing something similar for your case.

I don't like the CommandOption approach, as the whole purpose of the `at.Command()` method is to perform an AT command transaction.
I would add a separate method that doesn't prefix the AT, or does the complete transaction like `SMSCommand()`, but again I need a better understanding of your use case to be sure.

**Comment by n-elia** [comment]
Thanks for your kind explanation! I fully agree with everything.

You're right, my use case is very similar to SMS one. I have a Simcom module which prompts ">" after sending the initial AT command. The only difference is that I get a confirmation message from the modem, "SEND OK", after having escaped the data sending. I can easily parse the confirmation line: following your SMS example, I created [my own command](https://github.com/n-elia/modem/commit/ea8239ee227f71fcda4c9dadd5f0a083e8761a0c) which parses the "SEND OK" confirmation message. 
I hope that this will be helpful for future visitors.

Again, thank you very much for your help,
have a nice day!
Nicola
