### ISSUE TITLE
[BUG] AT+COPS reset

### ISSUE THREAD

**Issue by kenstel** [warthog618/modem#16]
Hi,
I am trying to select network manually using the command
` +COPS?`
 +COPS: 0,0, "<my carrier name>", ,7 //got reply

`+COPS=2`
AT+COPS=2 //got reply

But then, when I try to fetch my network configurations again using the command:
` +COPS?`

I get this (without //got reply):
 +COPS: 0 //got reply

I am able to use this command correctly using python atcom package. Any ideas where it went wrong?
I am using https://github.com/warthog618/modem/blob/master/cmd/modeminfo/modeminfo.go as base with /dev/ttyUSB0 as my device and commands +CIMI,+CSQ etc. works absolutely fine.

**Comment by warthog618** [comment]
No idea.  If the problem is due to this library I would have to see a full trace of both the atcom successes and the failures to compare.
What is the +COPS=2 supposed to do exactly?

**Comment by kenstel** [comment]
Basically Problem is this Suppose if we run any AT command then it will change my network mode from Manual to Automatic.
Example:
AT+COPS? ==> This command will return the current network mode(Automatic/Manual)
AT+COPS=1,1,"airtel" ==> This command will change my network mode to Manual.

After that if we run any AT command then it will change my network mode back to Automatic.

**Comment by warthog618** [comment]
Why would it do that - unless you are creating a new modem instance?
