### ISSUE TITLE
2023/05/01 15:40:55 waitsms.go:75: CMS Error: unknown

### ISSUE THREAD

**Issue by codenoid** [warthog618/modem#17]
```
ATI
 FOXCOM MODEM
 Quectel_M26
 Revision: M26FBR03A04_TTS
AT+GCAP
 +GCAP: +CGSM,+FCLASS
AT+CMEE=2
AT+CGMI
 FOXCOM MODEM
AT+CGMM
 Quectel_M26
AT+CGMR
 Revision: M26FBR03A06-TTS
AT+CGSN
 012345678912345
AT+CSQ
 +CSQ: 28,0
AT+CIMI
 510019568278473
AT+CREG?
 +CREG: 0,5
AT+CNUM
AT+CPIN?
 +CPIN: READY
AT+CEER
 +CEER: 0,0
AT+CSCA?
 +CSCA: "+62816124",145
AT+CSMS?
 +CSMS: 0,1,1,1
AT+CSMS=?
 +CSMS: (0,128)
AT+CPMS=?
 +CPMS: ("SM","ME","MT"),("SM","ME","MT"),("SM","ME","MT")
AT+CCID?
 +CCID: "89620160002701055486"
AT+CCID=?
 +CCID: "89620160002701055486"
AT^ICCID?
 CME Error: unknown
AT+CNMI?
 +CNMI: 2,1,0,0,0
AT+CNMI=?
 +CNMI: (0-3),(0-3),(0,2,3),(0-2),(0,1)
AT+CNMA=?
 +CNMA: (0-2)
AT+CMGF?
 +CMGF: 0
AT+CMGF=?
 +CMGF: (0,1)
AT+CUSD?
 +CUSD: 0
AT+CUSD=?
AT^USSDMODE?
 CME Error: unknown
AT^USSDMODE=?
 CME Error: unknown
```

**Comment by codenoid** [comment]
sorry, the wait sms log that erroring are:

```
2023/05/01 15:42:27 w: 

023/05/01 15:42:27 w: ATZ
2023/05/01 15:42:27 r:
2023/05/01 15:42:27 r:
OK
2023/05/01 15:42:27 w: ATE0
2023/05/01 15:42:27 r:
2023/05/01 15:42:27 r:
OK
2023/05/01 15:42:27 w: AT+GCAP
2023/05/01 15:42:27 r:
2023/05/01 15:42:27 r:
+GCAP: +CGSM,+FCLASS

OK
2023/05/01 15:42:27 w: AT+CMGF=0
2023/05/01 15:42:27 r:
2023/05/01 15:42:27 r:
OK
2023/05/01 15:42:27 w: AT+CMEE=2
2023/05/01 15:42:27 r: 
2023/05/01 15:42:27 r:
OK
2023/05/01 15:42:27 w: AT+CSMS=1
2023/05/01 15:42:27 r:
2023/05/01 15:42:27 r:
+CMS ERROR: unknown
2023/05/01 15:42:27 waitsms.go:75: CMS Error: unknown
```

**Comment by warthog618** [comment]
Note the comment at the top of waitsms.go:

// This provides an example of using indications, as well as a test that the
// library works with the modem.

So what are you expecting to see?  Is the AT+CSMS=1 command supported by your modem?

**Comment by codenoid** [comment]
thanks for the response, how do i check what supported in my modem?

**Comment by warthog618** [comment]
Ah, I should've scrolled up further... 
Your modem reported:

```
AT+CSMS=?
 +CSMS: (0,128)
```
so it supports 0 or 128, but not 1 - most modems use 1.  So you need to override the init commands - to set it to 128(??) - you should check the manual for your modem to be sure, but assuming 0 is to disable SMS....

You need to patch waitsms.go:
```
diff --git a/cmd/waitsms/waitsms.go b/cmd/waitsms/waitsms.go
index 8cb6bd1..677c50c 100644
--- a/cmd/waitsms/waitsms.go
+++ b/cmd/waitsms/waitsms.go
@@ -68,7 +68,8 @@ func main() {
                },
                func(err error) {
                        log.Printf("err: %v\n", err)
-               })
+               },
+               gsm.WithInitCmds("+CSMS=128", "+CNMI=1,2,0,0,0"))
        if err != nil {
                log.Println(err)
                return
```

Hopefully that is the right option.
See if that works any better, or at least differently.

**Comment by codenoid** [comment]
wow thanks a lot, it's working now

**Comment by warthog618** [comment]
Glad to hear it.

I had considered making the library check the +CSMS=? result and use the second value, but being too clever tends to come back and bite you when you least expect it, so I prefer to require the explicit override if you need it, as above.

**Comment by codenoid** [comment]
__but being too clever tends to come back and bite you when you least expect it__

I agree with this

anyway, can you give me reference about `"+CSMS=128", "+CNMI=1,2,0,0,0"`, I would like to learn more about this kind of AT Command

**Comment by warthog618** [comment]
Good question.
The GSM command set is standard, but open to some interpretation, so you really need the manual for a specific modem to be sure on the meaning of the specific field values.
This [command set](https://www.sparkfun.com/datasheets/Cellular%20Modules/AT_Commands_Reference_Guide_r0.pdf) or [this](https://docs.rs-online.com/5931/0900766b80bec52c.pdf) are probably as good a place to start as any.
They both have the typical CSMS=? -> (0,1), so not your Quectel_M26 modem.
Couldn't find a manual for yours with a quick search, but you might have better luck.
