### ISSUE TITLE
Handling URCs with binary data

### ISSUE THREAD

**Issue by stefanalt** [warthog618/modem#19]
I currently experimenting with a Bluetooth low energy modem and your module.
Much is to my likeing.

However, I have to deal with URCs of this form (having a counted number of binary bytes following the first line):

`2024/01/27 21:08:15 r: "+QBLERECV:0,4A414E5A000000000000000000000101,6\r\n\x01\0x2\r\r\x00\xff"`

I think this can not be handled out of the box right now. I noticed your interrest is not in handling data,
but neverthesless an extenion like this might be useful:

````
    r := regexp.MustCompile(`^+QBLERECV:0,[0-9a-FA-F]{32},(?P<dtlen>[0-9]+)`)
   datahandler := func(info string, data []byte) {
	 ...
    }
    modem.AddDataIndication(r, datahandler)
````
what do you think?

**Comment by warthog618** [comment]
My first question is why aren't you using a bluetooth stack - why do you need to talk to the bluetooth modem yourself?

The current response parsing is very line based.  To extend it to handle a generalised form of your use case would be so general that I'm not sure what it would add compared to you wrapping the io.ReadWriter that you provide the AT to provide your own custom response pre-processing.
