### ISSUE TITLE
ATD+(xxxxxx...) context deadline exceeded

### ISSUE THREAD

**Issue by googolgl** [warthog618/modem#2]
Don`t support dial from AT command.
>ATD+[xxxxx...]
context deadline exceeded

**Comment by warthog618** [comment]
It would be useful to know how your modem responds to the ATD command.
Note that the modem code expects an OK from the modem, which you may not get until the called party answers, or alternatively an ERROR if something goes wrong.  If it sees neither of those within the time you set in your context then you will get the deadline exceeded you are seeing.

How does your modem respond if you perform the ATD manually?

**Comment by googolgl** [comment]
Hm
If i send symbol (;) in end, that's all work.
```
ATD+XXXXXXXXX;
OK
```

**Comment by warthog618** [comment]
Depends what you are trying to do.

With the ";" the modem interprets the request as a voice call and returns immediately returns an OK and returns to command mode.  So it behaves like a standard command.  You then monitor the call state with repeated AT+CLCC calls, and when the call ends use AT+CEER to check the failure reason.  And you use can use ATH to end the call from your end. 
The audio for the voice call is streamed through another serial port and so is independent of the command path that my modem driver is managing.  That is assuming your modem supports the audio stream.

Without the trailing ";" the modem interprets the ATD request as being for a data call, and the handshake is unlike other commands - it completes with either CONNECT when the other end answers, or BUSY, NO ANSWER, NO CARRIER or NO DIALTONE, depending the underlying failure cause.  I've just pushed a patch that should handle that handshake, in case that is what you want, though I haven't tested it with actual hardware yet.  Even if the handshake works, the modem will then be in data mode, and I haven't updated the driver to deal with that yet - or even thought about how to handle it.
