### ISSUE TITLE
SMS Recipet Request

### ISSUE THREAD

**Issue by xCoderly** [warthog618/modem#3]
Hello,

Can you please implement the Delivery Receipt,

check out this page: http://rednaxela.net/pdu.php

i mean to enable the receipt on message when its delivered i will get a Delivery Receipt Confirmation.

Thank you for this helpfull package.

**Comment by warthog618** [comment]
You mean in sendsms?  That is only intended to be an example of the modem library in use, not a comprehensive SMS sending tool.  You are more than welcome to modify it for your own purposes.  

To set the TP-SRR bit which you are referring to, you would need to provide a template of the Submit message to the message encoder:

@@ -66,6 +66,9 @@ func sendPDU(ctx context.Context, g *gsm.GSM, number string, msg string) {
        }
        ude.AddAllCharsets()
        me := message.NewEncoder(ude, sar.NewSegmenter())
+       submit := tpdu.NewSubmit()
+       submit.FirstOctet |= 0x20
+       me.SetT(submit)
        pdus, err := me.Encode(number, msg)
        if err != nil {

That should set the bit in the outgoing PDUs.  And you would also have to wait for and handle the status reports that should be returned.  You could use the code from waitsms.go as the basis of doing that.
