### ISSUE TITLE
How to send USSD and wait for response

### ISSUE THREAD

**Issue by giautm** [warthog618/modem#5]
I want to send USSD code to monitor account balancer. Currently, I have to convert `*101#` to 7bit package as `AA182C3602`. Then, send in CUSD command `+CUSD=1,"AA182C3602",15`. The next step to do is call `AddIndication` with `+CUSD`, then decode the response from 7bit to UTF-8 string.

How to make it more simple? 😄 

`gsm7.Pack7BitUSSD` was not just related to SMS, but USSD too. So it should live in an another package?

**Comment by warthog618** [comment]
You can write a function to do all that - all the bits you need are there.  How you would want to structure that depends on your use case, i.e. what else you are doing with the modem.  Note that you should *AddIndication* before you issue the **CUSD**, then wait for your handler to deal with the response.  And you should *CancelIndication* once the command completes.

The *gsm7.Pack7BitUSSB* is happy where it is.  That library deals with packing and unpacking GSM 7bit, and is applicable to GSM, USSD and MMI.  That happens to be a subpackage of my SMS package, but that doesn't prevent it from being used elsewhere, in fact that is exactly why it is in a subpackage.

**Comment by warthog618** [comment]
A basic USSD example added in 43b5a0a.

**Comment by giautm** [comment]
Thank you for nice example. I'm new to GSM module. I don't know if any other place applies such encoding steps? 🤔 
```go
	hmsg := strings.ToUpper(hex.EncodeToString(gsm7.Pack7BitUSSD([]byte(ussdCode), 0)))
```
```go
	fields := strings.Split(info.TrimPrefix(rsp, "+CUSD"), ",")
	rspb, _ := hex.DecodeString(strings.Trim(fields[1], "\""))
	rspb = gsm7.Unpack7BitUSSD(rspb, 0)
```

One more, 
```go
	cmd := fmt.Sprintf(`+CUSD=1,"%s",%d`, hmsg, 15)
	_, err = g.Command(cmd)
```
maybe consider to `g.Commandf("+CUSD=1,\"%s\",%d", hmsg, 15)`?

**Comment by warthog618** [comment]
I'm not sure what you are suggesting.  You want one function to do all that?  The whole point of providing libraries like this is that they can be combined as necessary under different circumstances to produce different outcomes. For example  my modem didn't like the lower case hex that *hex.EncodeToString* (a standard library function) produces, so I wrap it in *strings.ToUpper* to fix that.  Combining all that into one function would just produce fragile code.  Or would you prefer I didn't chain the calls??

Wrt decoding the response, I go to fields in one line.  I happen to be interested displaying the middle field that happens to be quoted, hex encoded and 7 bit packed.  That requires a few steps to decode, again using standard library calls for the most part.  *hex.DecodeString* returns an error so I can't chain it directly into *gsm7.Unpack7BitUSSD*, so it has to be split over two lines.  And robust code would check the errors, but this is just an example.

That works for me.  Feel free to write your own improvements.

The *Command* method already has variadic args, to alter its behaviour, which would conflict with the variadic args required for the *Commandf* approach - you would gain formatting and lose all the other options.  Adding a formatting option would be no shorter or clearer than using *fmt.Sprintf* directly. And of course there are plenty of other functions that return string that you could use as well...

**Comment by giautm** [comment]
Thanks for the explanation,

I just don't know in other AT commands, whenever I have to code it like the above steps. This may result in repeated snippets of code during operation with the GSM module.

I have noticed that some devices run the USSD command without having to encode it into a 7-bit packet. Is this difference due to PDU mode?
