### ISSUE TITLE
Can't connect to HUAWEI modem

### ISSUE THREAD

**Issue by giautm** [warthog618/modem#6]
Previously, I successfully connected to the Huawei `12d1:1506` modem. I am currently trying to connect to another Huawei device with the same vid/pid, but it failed.

However, when using [gammu-smsd](https://github.com/gammu/gammu), the software can still connect and receive messages.

I have attached AT log information, and device information taken from the lsusb command.
Can you help me?, Thank you.

https://gist.github.com/giautm/dcec3199abae1504f1fcfddad8e7a652

**Comment by warthog618** [comment]
Yeah, no not really - not familiar with that model, and this looks like a hardware configuration problem. I would guess that either your modem is in the wrong mode, or you are using the wrong tty (modems often have several), or something else is also using that modem via one of the other ttys.  You could also hex dump the logs - that might give you a better idea where the non-ASCII characters are originating.

**Comment by giautm** [comment]
Close this issue, because for unknown reasons. Currently the device works with Orange Pi Zero. The previous device that failed is Raspberry 2. :v
