### ISSUE TITLE
Unable get ERROR from USSD

### ISSUE THREAD

**Issue by giautm** [warthog618/modem#9]
I try to run a USSD code that my carrier not supported. But, It still return success (first line with OK), then second line is `+CME ERROR`. That error never return as error in `Command()` function. You can try to use USSD example and run any code that not support, the result will be the same as expected.

```
w: AT+CUSD=1,\"AA584C3602\",15\r\n,
r: \r\nOK\r\n,
r: \r\n+CME ERROR: service option not supported\r\n,
```

**Comment by giautm** [comment]
When I try to send raw text as `AT+CUSD=1,"*112#",15`. The result returned is successful. How I can detect, which the modem/mode need to be encode/decode text?

**Comment by warthog618** [comment]
I can't reproduce your problem so I can only guess...
The error is asynchronous, so you could add a "+CME ERROR:" handler to look for the CME errors, similar  to how the ussd.go example looks for "+CUSD:" lines?

"AT^USSDMODE?" determines whether the data needs to be encoded?

**Comment by giautm** [comment]
Yes, the error is asynchronous. But, I don't like to add two AddIndications to handle simple USSD case. `+CME ERROR` is more common, may added by another function that also require to handle `+CME ERROR`. That lead to a duplicated error.

I thinking about new API like under, but I don't know how to resolve duplicate case.

```go

type multiStrings []string

func Strings(s ...string) {
	return multiStrings(s)
}

func (s multiStrings) MatchPrefix(s string) bool {
	for _, ss := range s {
		if strings.HasPrefix(s, ss) {
			return true
		}
	}
	return false
}

cancel, err := g.AddIndication(at.Strings("+CUSD:", "+CME ERROR:"), func(lines []string) {
	rspChan <- info.TrimPrefix(lines[0], "+CUSD")
})
if err != nil {
	return "", fmt.Errorf("failed to add command indication handler: %w", err)
}
defer cancel()
```
> "AT^USSDMODE?" determines whether the data needs to be encoded?
I can't found any document about this command in my device spec (MC55i), may it's not supported.

**Comment by warthog618** [comment]
I don't see any need for an API change - you can implement your suggestion on top of the existing API.

But I wouldn't do that - I would serialise the commands that can generate async errors so only one can be outstanding at a time.  I would have a handler for the errors that directs then to an errChan.  The handler for the outstanding command would wait for the response or the error, so select on the rspChan and errChan.

You may also be able to determine the command associated with the error from the error message.  Again, that is at a higher level than this library is targeted.

The "^USSDMODE" may be Huawei specific.  You may have to tailor your code to suit the particular modems you are driving, based whatever identifying information your modems can provide.

**Comment by giautm** [comment]
>I would have a handler for the errors that directs then to an errChan. The handler for the outstanding command would wait for the response or the error, so select on the rspChan and errChan.

Do you think about a utility function/receiver inside the AT package to resolve that problem?
```go
func errChan(a *at.AT) (<-chan error, func(), error) {
	errChan := make(chan error)
	var err error
	err = a.AddIndication("+CME ERROR:", func(lines []string) {
		errChan <- at.CMEError(strings.TrimSpace(lines[0][11:]))
	})
	if err != nil {
		return nil, nil, err
	}
	err = a.AddIndication("+CMS ERROR:", func(lines []string) {
		errChan <- at.CMSError(strings.TrimSpace(lines[0][11:]))
	})
	if err != nil {
		a.CancelIndication("+CME ERROR:")
		return nil, nil, err
	}

	err = a.AddIndication("ERROR:", func(_ []string) {
		errChan <- at.ErrError
	})
	if err != nil {
		a.CancelIndication("+CME ERROR:")
		a.CancelIndication("+CMS ERROR:")
		return nil, nil, err
	}

	return errChan, func() {
		a.CancelIndication("ERROR:")
		a.CancelIndication("+CMS ERROR:")
		a.CancelIndication("+CME ERROR:")
		close(errChan)
	}, nil
}
```

```diff
+	errChan, cleanup, err := errChan(m.gsm.AT)
+	if err != nil {
+		return "", err
+	}
+	defer cleanup()

	_, err = g.Command(fmt.Sprintf("+CUSD=1,\"%s\",15", encode(code)))
	if err != nil {
		return "", fmt.Errorf("failed to send USSD code: %w", err)
	}

	select {
	case <-time.After(time.Second * 5):
		return "", ErrNoResponse
+	case err := <-errChan:
+		return "", err
	case rsp := <-rspChan:
``
